name:                optic-lang
version:             0.1.0.0
github:              "Skyb0rg007/optic-lang"
license:             BSD3
author:              "Skye Soss"
maintainer:          "Skye Soss <skyler.soss@gmail.com>"
copyright:           "2019 Skye Soss"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Programming language with first-class lenses
category:            Compilers/Interpreters

description: Please see the README on GitHub at <https://github.com/Skyb0rg007/optic-lang#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- bound
- bytestring
- containers
- deepseq
- grin
- lens
- megaparsec
- mtl
- parser-combinators
- prettyprinter
- text
- transformers-compat

library:
  source-dirs: src

executables:
  optic-lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optic-lang

tests:
  optic-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - silently
    - optic-lang
